apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  application.yml: |-
{{ .Values.config.applicationYaml | nindent 4 }}
  metaForDoc.json: |-
{{ .Values.config.metaForDocJson | nindent 4 }}
  metaspec.json: |-
{{ .Values.config.metaspecJson | nindent 4 }}
